## Data Preparation

In [1]:
import json
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoConfig

### Steps

In [2]:
path = r"D:\Dafa\Project\queryner-kd\data\processed\train.json"
with open(path, "r", encoding="utf-8") as f:
    raw = json.load(f)["examples"]

print(len(raw))
for item in raw[:2]:
    print(item)

7823
{'tokens': ['teeth', 'whitening', 'sensitive', 'teeth'], 'ner_tags': [9, 10, 17, 18]}
{'tokens': ['white', 'duvet', 'cover', 'queen'], 'ner_tags': [3, 9, 10, 1]}


In [3]:
tokens = raw[0]["tokens"]
ner_tags = raw[0]["ner_tags"]
print(tokens)
print(ner_tags)

['teeth', 'whitening', 'sensitive', 'teeth']
[9, 10, 17, 18]


In [4]:
model_name = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [5]:
encodings = tokenizer(
            tokens,
            is_split_into_words=True,
            truncation=True,
            padding="max_length",
            max_length=128,
            return_tensors="pt",
        )
encodings

{'input_ids': tensor([[ 101, 4091, 2317, 5582, 7591, 4091,  102,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0,

In [6]:
word_ids = encodings.word_ids(batch_index=0)
print(word_ids)

[None, 0, 1, 1, 2, 3, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]


In [7]:
encodings["input_ids"][0]

tensor([ 101, 4091, 2317, 5582, 7591, 4091,  102,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0])

In [8]:
aligned_labels = []
previous_word_idx = None
for word_idx in word_ids:
    if word_idx is None:
        aligned_labels.append(-100)
    elif word_idx != previous_word_idx:
        aligned_labels.append(ner_tags[word_idx])
    else:
        aligned_labels.append(-100)
    previous_word_idx = word_idx

print(aligned_labels)

[-100, 9, 10, -100, 17, 18, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100]


In [9]:
item = {
    "input_ids": encodings["input_ids"].squeeze(0),
    "attention_mask": encodings["attention_mask"].squeeze(0),
    "labels": torch.tensor(aligned_labels, dtype=torch.long)
}
print(item)

{'input_ids': tensor([ 101, 4091, 2317, 5582, 7591, 4091,  102,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]), 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0

In [10]:
class NERDataset(Dataset):
    def __init__(self, data_path, tokenizer, label_pad_id=-100, max_length=128):
        ## khusus untuk data json
        with open(data_path, "r", encoding="utf-8") as f:
            raw = json.load(f)["examples"]
        self.data = raw
        self.tokenizer = tokenizer
        self.label_pad_id = label_pad_id
        self.max_length = max_length

    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        tokens = self.data[idx]["tokens"]
        ner_tags = self.data[idx]["ner_tags"]

        # buat encoding untuk tokens 
        encoding = self.tokenizer(
            tokens,
            is_split_into_words=True,
            truncation=True,
            padding='max_length',
            max_length=self.max_length,
            return_tensors="pt"
        )

        # align labels dengan tokens yang sudah diencoding (jadi kepotong2 sesuai tokenization)
        word_ids = encoding.word_ids(batch_index=0)
        aligned_labels = []
        previous_word_idx = None
        for word_idx in word_ids:
            if word_idx is None:
                aligned_labels.append(self.label_pad_id)
            elif word_idx != previous_word_idx:
                aligned_labels.append(ner_tags[word_idx])
            else:
                aligned_labels.append(self.label_pad_id)
            previous_word_idx = word_idx
        
        item = {
            "input_ids": encoding["input_ids"].squeeze(0),
            "attention_mask": encoding["attention_mask"].squeeze(0),
            "labels": torch.tensor(aligned_labels, dtype=torch.long)
        }

        return item

In [11]:
def load_label_info(model_name):
    config = AutoConfig.from_pretrained(model_name)
    id2label = config.id2label
    label2id = config.label2id
    num_labels = config.num_labels

    label_info = {
        "id2label": id2label,
        "label2id": label2id,
        "num_labels": num_labels
    }

    return label_info

def create_dataloaders(
        train_path, val_path, test_path,
        model_name,
        batch_size=16,
        max_length=128
):
    tokenizer = AutoTokenizer.from_pretrained(model_name)

    train_dataset = NERDataset(train_path, tokenizer, max_length=max_length)
    val_dataset = NERDataset(val_path, tokenizer, max_length=max_length)
    test_dataset = NERDataset(test_path, tokenizer, max_length=max_length)

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    return train_loader, val_loader, test_loader

In [ ]:
label_info = load_label_info()

In [12]:
train_dataset = NERDataset(
    data_path=r"D:\Dafa\Project\queryner-kd\data\processed\train.json",
    tokenizer=tokenizer
)
train_dataset

In [13]:
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
train_loader

In [14]:
batch = next(iter(train_loader))
batch

{'input_ids': tensor([[  101, 26717, 14694,  ...,     0,     0,     0],
         [  101, 29250, 13382,  ...,     0,     0,     0],
         [  101,  2308,  2304,  ...,     0,     0,     0],
         ...,
         [  101, 23445, 19691,  ...,     0,     0,     0],
         [  101,  5898,  2849,  ...,     0,     0,     0],
         [  101,  2300,  5835,  ...,     0,     0,     0]]),
 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]]),
 'labels': tensor([[-100,   17,    9,  ..., -100, -100, -100],
         [-100,    9,   10,  ..., -100, -100, -100],
         [-100,   13,    3,  ..., -100, -100, -100],
         ...,
         [-100,   11,   25,  ..., -100, -100, -100],
         [-100,   15,    9,  ..., -100, -100, -100],
         [-100,    9,   10,  ..., -100, -100, -100]])}

### Run

In [1]:
import json
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoConfig

In [2]:
class NERDataset(Dataset):
    def __init__(self, data_path, tokenizer, label_pad_id=-100, max_length=128):
        with open(data_path, "r", encoding="utf-8") as f:
            raw = json.load(f)["examples"]
        self.data = raw
        self.tokenizer = tokenizer
        self.label_pad_id = label_pad_id
        self.max_length = max_length

    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        tokens = self.data[idx]["tokens"]
        ner_tags = self.data[idx]["ner_tags"]

        # buat encoding untuk tokens 
        encoding = self.tokenizer(
            tokens,
            is_split_into_words=True,
            truncation=True,
            padding='max_length',
            max_length=self.max_length,
            return_tensors="pt"
        )

        # align labels dengan tokens yang sudah diencoding (jadi kepotong2 sesuai tokenization)
        word_ids = encoding.word_ids(batch_index=0)
        aligned_labels = []
        previous_word_idx = None
        for word_idx in word_ids:
            if word_idx is None:
                aligned_labels.append(self.label_pad_id)
            elif word_idx != previous_word_idx:
                aligned_labels.append(ner_tags[word_idx])
            else:
                aligned_labels.append(self.label_pad_id)
            previous_word_idx = word_idx
        
        item = {
            "input_ids": encoding["input_ids"].squeeze(0),
            "attention_mask": encoding["attention_mask"].squeeze(0),
            "labels": torch.tensor(aligned_labels, dtype=torch.long)
        }

        return item

In [3]:
def load_label_info(model_name):
    config = AutoConfig.from_pretrained(model_name)
    id2label = config.id2label
    label2id = config.label2id
    num_labels = config.num_labels

    label_info = {
        "id2label": id2label,
        "label2id": label2id,
        "num_labels": num_labels
    }

    return label_info

def create_dataloaders(
        train_path, val_path, test_path,
        model_name,
        batch_size=32,
        max_length=128
):
    tokenizer = AutoTokenizer.from_pretrained(model_name)

    train_dataset = NERDataset(train_path, tokenizer, max_length=max_length)
    val_dataset = NERDataset(val_path, tokenizer, max_length=max_length)
    test_dataset = NERDataset(test_path, tokenizer, max_length=max_length)

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    return train_loader, val_loader, test_loader

In [4]:
train_loader, val_loader, test_loader = create_dataloaders(
    train_path=r"D:\Dafa\Project\queryner-kd\data\processed\train.json",
    val_path=r"D:\Dafa\Project\queryner-kd\data\processed\validation.json",
    test_path=r"D:\Dafa\Project\queryner-kd\data\processed\test.json",
    model_name="bert-base-uncased",
    batch_size=16,
    max_length=128
)

label_info = load_label_info("bltlab/queryner-augmented-data-bert-base-uncased")

In [5]:
batch = next(iter(train_loader))
batch

{'input_ids': tensor([[  101, 27133,  8883,  ...,     0,     0,     0],
         [  101, 14123,  2015,  ...,     0,     0,     0],
         [  101,  6910,  3259,  ...,     0,     0,     0],
         ...,
         [  101,  2190,  7071,  ...,     0,     0,     0],
         [  101,  5717,  4530,  ...,     0,     0,     0],
         [  101,  2227,  7308,  ...,     0,     0,     0]]),
 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]]),
 'labels': tensor([[-100,   11, -100,  ..., -100, -100, -100],
         [-100,    9, -100,  ..., -100, -100, -100],
         [-100,   17,   15,  ..., -100, -100, -100],
         ...,
         [-100,   17,    9,  ..., -100, -100, -100],
         [-100,   11,   12,  ..., -100, -100, -100],
         [-100,    9,   10,  ..., -100, -100, -100]])}

In [9]:
from torch import nn
from torchcrf import CRF
from transformers import AutoModel, AutoConfig

In [10]:
# BaseNERModel
label_info = label_info
use_crf = False

# QueryNER
model_name = "bert-base-uncased"
config = AutoConfig.from_pretrained(
    model_name,
    num_labels=label_info["num_labels"],
    id2label=label_info["id2label"],
    label2id=label_info["label2id"]
)

bert = AutoModel.from_pretrained(model_name, config=config)
dropout = nn.Dropout(0.1)
classifier = nn.Linear(bert.config.hidden_size, bert.config.num_labels)
loss_fn = nn.CrossEntropyLoss(ignore_index=-100)

In [11]:
# forward
outputs = bert(input_ids=batch["input_ids"], attention_mask=batch["attention_mask"])
outputs.last_hidden_state.shape  # (batch_size, seq_len, hidden_size)

torch.Size([16, 128, 768])

In [12]:
sequence_output = dropout(outputs.last_hidden_state)
sequence_output.shape

torch.Size([16, 128, 768])

#### Use CRF False

In [13]:
logits = classifier(sequence_output)  # (batch_size, seq_len, num_labels)
logits.shape

torch.Size([16, 128, 35])

In [14]:
loss = loss_fn(
    logits.view(-1, label_info["num_labels"]),
    batch["labels"].view(-1)
)
loss

tensor(3.6103, grad_fn=<NllLossBackward0>)

#### Use CRF True

In [24]:
from torchcrf import CRF
# input nya sequence_output, labels, mask
fc = nn.Linear(bert.config.hidden_size, bert.config.num_labels)
crf = CRF(label_info["num_labels"], batch_first=True)

In [25]:
emissions = fc(sequence_output)  # (batch_size, seq_len, num_labels)
emissions.shape

torch.Size([16, 128, 35])

In [26]:
batch["labels"] is not None

True

In [27]:
batch["labels"]

tensor([[ 0, 11,  0,  ...,  0,  0,  0],
        [ 0,  9,  0,  ...,  0,  0,  0],
        [ 0, 17, 15,  ...,  0,  0,  0],
        ...,
        [ 0, 17,  9,  ...,  0,  0,  0],
        [ 0, 11, 12,  ...,  0,  0,  0],
        [ 0,  9, 10,  ...,  0,  0,  0]])

In [28]:
mask = batch["attention_mask"]
mask = mask.bool()
mask[:, 0] = True

In [29]:
labels_crf = batch["labels"]
labels_crf[batch["labels"] == -100] = 0
labels_crf

tensor([[ 0, 11,  0,  ...,  0,  0,  0],
        [ 0,  9,  0,  ...,  0,  0,  0],
        [ 0, 17, 15,  ...,  0,  0,  0],
        ...,
        [ 0, 17,  9,  ...,  0,  0,  0],
        [ 0, 11, 12,  ...,  0,  0,  0],
        [ 0,  9, 10,  ...,  0,  0,  0]])

In [30]:
log_likehood = crf(emissions, batch["labels"], mask=batch["attention_mask"].bool(), reduction='token_mean')
loss = -log_likehood
loss

tensor(3.5940, grad_fn=<NegBackward0>)

In [31]:
pred = crf.decode(emissions, mask=batch["attention_mask"].bool())
pred

[[4, 20, 28, 28, 2, 21],
 [23, 1, 28, 28, 28, 21],
 [4, 13, 4, 20, 24, 15, 28, 28, 21],
 [4, 1, 32, 4, 14, 27, 27, 1, 15, 2, 15, 0],
 [7, 18, 23, 18, 27, 13, 21],
 [4, 12, 28, 16, 16, 16, 28, 21],
 [21, 10, 23, 27, 4, 13, 4, 21],
 [18, 28, 28, 28, 28, 28, 28, 29, 18, 28, 21],
 [18, 28, 7, 17, 28, 28, 21],
 [13, 2, 2, 21],
 [23, 28, 7, 4, 23],
 [4, 13, 18, 4, 4, 21],
 [11, 18, 4, 20, 4, 0, 21],
 [7, 13, 9, 28, 28, 28, 21],
 [13, 18, 27, 2, 27, 29, 18, 21],
 [13, 20, 29, 4, 21]]

## Model Architecture

### Class

In [32]:
from torch import nn
from torchcrf import CRF
from transformers import AutoModel, AutoConfig

In [33]:
class CRFOutputLayer(nn.Module):
    def __init__(self, hidden_dim, num_labels):
        super().__init__()
        self.fc = nn.Linear(hidden_dim, num_labels)
        self.crf = CRF(num_tags=num_labels, batch_first=True)

    def forward(self, outputs, labels=None, mask=None):
        emissions = self.fc(outputs)

        if labels is not None:
            if mask is None:
                mask = torch.ones_like(labels, dtype=torch.bool)
            else:
                mask = mask.bool()
            
            mask[:, 0] = True
            
            labels_crf = labels.clone()
            labels_crf[labels == -100] = 0
            
            log_likelihood = self.crf(emissions, tags=labels_crf, mask=mask, reduction="token_mean")
            loss = -log_likelihood
            return {"logits": emissions, "loss": loss}
        else:
            if mask is None:
                mask = torch.ones(outputs.shape[:2], dtype=torch.bool, device=outputs.device)
            pred = self.crf.decode(emissions, mask=mask.bool())
            return {"logits": emissions, "pred": pred}

In [34]:
class BaseNERModel(nn.Module):
    def __init__(self, num_labels, use_crf=False):
        super().__init__()
        self.num_labels = num_labels
        self.use_crf = use_crf

    def forward(self, input_ids, attention_mask, labels=None):
        raise NotImplementedError("Forward method must be implemented in subclass.")

In [35]:
class QueryNERTeacher(BaseNERModel):
    def __init__(self, model_name, label_info, use_crf=False):
        super().__init__(num_labels=label_info["num_labels"], use_crf=use_crf)

        self.config = AutoConfig.from_pretrained(
            model_name,
            num_labels=label_info["num_labels"],
            id2label=label_info["id2label"],
            label2id=label_info["label2id"]
        )

        self.bert = AutoModel.from_pretrained(model_name, config=self.config)
        self.dropout = nn.Dropout(0.3)

        if self.use_crf:
            self.crf_output = CRFOutputLayer(self.config.hidden_size, self.config.num_labels)
        else:
            self.classifier = nn.Linear(self.config.hidden_size, self.config.num_labels)
            self.loss_fn = nn.CrossEntropyLoss(ignore_index=-100)

    def forward(self, input_ids, attention_mask, labels=None):

        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        sequence_output = self.dropout(outputs.last_hidden_state)

        if self.use_crf:
            mask = attention_mask.bool()
            result = self.crf_output(sequence_output, labels=labels, mask=mask)
            return result

        else:
            logits = self.classifier(sequence_output)
            if labels is not None:
                loss = self.loss_fn(logits.view(-1, self.num_labels), labels.view(-1))
                return {"logits": logits, "loss": loss}
            else:
                pred = logits.argmax(dim=-1)
                return {"logits": logits, "pred": pred}

In [36]:
class DistilBERTStudent(BaseNERModel):
    def __init__(self, model_name="distilbert-base-uncased", label_info=None, use_crf=False):
        self.use_crf = use_crf
        self.num_labels = label_info["num_labels"]
        super().__init__(num_labels=self.num_labels, use_crf=self.use_crf)

        self.config = AutoConfig.from_pretrained(
            model_name,
            num_labels=label_info["num_labels"],
            id2label=label_info["id2label"],
            label2id=label_info["label2id"]
        )

        self.bert = AutoModel.from_pretrained(model_name, config=self.config)
        self.dropout = nn.Dropout(0.3)

        if self.use_crf:
            self.crf_output = CRFOutputLayer(self.config.hidden_size, self.num_labels)
        else:
            self.classifier = nn.Linear(self.config.hidden_size, self.num_labels)
            self.loss_fn = nn.CrossEntropyLoss(ignore_index=-100)

    def forward(self, input_ids, attention_mask, labels=None):
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        sequence_output = self.dropout(outputs.last_hidden_state)

        if self.use_crf:
            mask = attention_mask.bool()
            result = self.crf_output(sequence_output, labels=labels, mask=mask)
            return result
        else:
            logits = self.classifier(sequence_output)
            if labels is not None:
                loss = self.loss_fn(logits.view(-1, self.num_labels), labels.view(-1))
                return {"logits": logits, "loss": loss}
            else:
                pred = logits.argmax(dim=-1)
                return {"logits": logits, "pred": pred}

In [37]:
class TinyBertStudent(BaseNERModel):
    def __init__(self, model_name="huawei-noah/TinyBERT_General_4L_312D", label_info=None, use_crf=False):
        self.use_crf = use_crf
        self.num_labels = label_info["num_labels"]
        super().__init__(num_labels=self.num_labels, use_crf=self.use_crf)

        self.config = AutoConfig.from_pretrained(
            model_name,
            num_labels=label_info["num_labels"],
            id2label=label_info["id2label"],
            label2id=label_info["label2id"]
        )

        self.bert = AutoModel.from_pretrained(model_name, config=self.config)
        self.dropout = nn.Dropout(0.3)

        if self.use_crf:
            self.crf_output = CRFOutputLayer(self.config.hidden_size, self.num_labels)
        else:
            self.classifier = nn.Linear(self.config.hidden_size, self.num_labels)
            self.loss_fn = nn.CrossEntropyLoss(ignore_index=-100)

    def forward(self, input_ids, attention_mask, labels=None):
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        sequence_output = self.dropout(outputs.last_hidden_state)

        if self.use_crf:
            mask = attention_mask.bool()
            result = self.crf_output(sequence_output, labels=labels, mask=mask)
            return result
        else:
            logits = self.classifier(sequence_output)
            if labels is not None:
                loss = self.loss_fn(logits.view(-1, self.num_labels), labels.view(-1))
                return {"logits": logits, "loss": loss}
            else:
                pred = logits.argmax(dim=-1)
                return {"logits": logits, "pred": pred}

In [38]:
class BiLSTMStudent(BaseNERModel):
    def __init__(
            self,  
            use_crf=False,
            model_name_for_vocab = 'bert-base-uncased',
            emb_dim = 300,
            lstm_hidden = 300,
            label_info = None,
            pad_token_id = 0,
            teacher_model = None
        ):
        self.use_crf = use_crf
        self.num_labels = label_info["num_labels"]
        super().__init__(self.num_labels, use_crf)

        config = AutoConfig.from_pretrained(model_name_for_vocab)
        vocab_size = config.vocab_size
        pad_token_id = config.pad_token_id

        if teacher_model is not None:
            self.embedding = teacher_model.bert.embeddings.word_embeddings
            for p in self.embedding.parameters():
                p.requires_grad = False
            emb_dim_eff = self.embedding.embedding_dim
        else:
            emb_dim_eff = emb_dim
            self.embedding = nn.Embedding(vocab_size, emb_dim, padding_idx=pad_token_id)
        self.dropout = nn.Dropout(0.1)
        self.lstm = nn.LSTM(
            input_size=emb_dim_eff,
            hidden_size=lstm_hidden,
            num_layers=1,
            batch_first=True,
            bidirectional=True
        )
        self.classifier = nn.Linear(lstm_hidden * 2, self.num_labels)
        self.loss_fn = nn.CrossEntropyLoss(ignore_index=-100)

        if self.use_crf:
            self.crf_output = CRFOutputLayer(hidden_dim=lstm_hidden * 2, num_labels=self.num_labels)

    def forward(self, input_ids, attention_mask, labels=None):
        emb = self.embedding(input_ids)
        emb = self.dropout(emb)
        outputs, _ = self.lstm(emb)
        sequence_output = outputs

        if self.use_crf:
            mask = attention_mask.bool()
            result = self.crf_output(sequence_output, labels=labels, mask=mask)
            return result
        else:
            logits = self.classifier(sequence_output)
            if labels is not None:
                loss = self.loss_fn(logits.view(-1, self.num_labels), labels.view(-1))
                return {"logits": logits, "loss": loss}
            else:
                pred = logits.argmax(dim=-1)
                return {"logits": logits, "pred": pred}

### Run

In [39]:
import torch.nn.functional as F

In [40]:
teacher = QueryNERTeacher("bert-base-uncased", label_info, use_crf=False)
student = DistilBERTStudent(label_info=label_info, use_crf=False)

In [41]:
batch = next(iter(train_loader))

input_ids = batch["input_ids"]
attention_mask = batch["attention_mask"]
labels = batch["labels"]

In [42]:
print("input_ids shape:", input_ids.shape)
print("attention_mask shape:", attention_mask.shape)
print("labels shape:", labels.shape)

input_ids shape: torch.Size([16, 128])
attention_mask shape: torch.Size([16, 128])
labels shape: torch.Size([16, 128])


In [43]:
t_result = teacher(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
print(t_result["logits"].shape)
print(t_result["logits"][:1, :1])
print(t_result["loss"])

torch.Size([16, 128, 35])
tensor([[[ 0.2587,  0.4176, -0.2309, -0.0158, -0.1463,  0.1423, -0.5015,
          -0.0292, -0.4604, -0.3602, -0.1373, -0.4531, -0.2994,  0.2807,
          -0.3041,  0.4166, -0.0764,  0.3931,  0.2293, -0.1002, -0.0475,
          -0.3097, -0.0734, -0.2026,  0.4468,  0.0101,  0.2102,  0.2191,
           0.3749,  0.4592,  0.0914, -0.0614,  0.2080,  0.3196, -0.1389]]],
       grad_fn=<SliceBackward0>)
tensor(3.6314, grad_fn=<NllLossBackward0>)


In [44]:
s_result = student(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
s_result.keys()

dict_keys(['logits', 'loss'])

## KL Div

In [46]:
T = 2.0

In [98]:
print(t_result["logits"][:1, :1, :35]/2.0)
print(s_result["logits"][:1, :1, :35]/2.0)

tensor([[[ 0.1294,  0.2088, -0.1154, -0.0079, -0.0732,  0.0711, -0.2508,
          -0.0146, -0.2302, -0.1801, -0.0686, -0.2266, -0.1497,  0.1404,
          -0.1521,  0.2083, -0.0382,  0.1966,  0.1147, -0.0501, -0.0237,
          -0.1549, -0.0367, -0.1013,  0.2234,  0.0050,  0.1051,  0.1096,
           0.1874,  0.2296,  0.0457, -0.0307,  0.1040,  0.1598, -0.0695]]],
       grad_fn=<DivBackward0>)
tensor([[[-0.2885, -0.0893, -0.0028, -0.0366, -0.0609,  0.0773, -0.0143,
           0.1353, -0.0084,  0.0931,  0.0773,  0.0024,  0.2517,  0.0942,
          -0.3847,  0.2916,  0.1550, -0.0641, -0.1222,  0.1847, -0.2785,
           0.0200, -0.0093,  0.1148, -0.0546, -0.1145,  0.0864, -0.0488,
          -0.0536,  0.2031, -0.1659, -0.0912, -0.1076,  0.0350,  0.1255]]],
       grad_fn=<DivBackward0>)


In [106]:
p_teacher = F.log_softmax(t_result["logits"]/T, dim=-1)   # (B, L, C) > (Batch, SeqLen, NumClasses) > (8, 128, 37)
print("Teacher ", p_teacher[:1, :1, :35])
print("Teacher ", p_teacher.shape)

p_student = F.softmax(s_result["logits"] / T, dim=-1)
print("Student", p_student[:1, :1])

Teacher  tensor([[[-3.4434, -3.3639, -3.6882, -3.5807, -3.6459, -3.5016, -3.8235,
          -3.5873, -3.8029, -3.7529, -3.6414, -3.7993, -3.7225, -3.4324,
          -3.7248, -3.3645, -3.6110, -3.3762, -3.4581, -3.6229, -3.5965,
          -3.7276, -3.6095, -3.6741, -3.3494, -3.5677, -3.4677, -3.4632,
          -3.3853, -3.3431, -3.5271, -3.6034, -3.4687, -3.4130, -3.6422]]],
       grad_fn=<SliceBackward0>)
Teacher  torch.Size([16, 128, 35])
Student tensor([[[0.0212, 0.0259, 0.0282, 0.0273, 0.0266, 0.0306, 0.0279, 0.0324,
          0.0281, 0.0311, 0.0306, 0.0284, 0.0364, 0.0311, 0.0193, 0.0379,
          0.0331, 0.0266, 0.0251, 0.0341, 0.0214, 0.0289, 0.0281, 0.0318,
          0.0268, 0.0253, 0.0309, 0.0270, 0.0268, 0.0347, 0.0240, 0.0258,
          0.0254, 0.0293, 0.0321]]], grad_fn=<SliceBackward0>)


In [115]:
kl = F.kl_div(p_teacher, p_student, reduction="none")
kl.shape

torch.Size([16, 128, 35])

In [116]:
kl.sum(dim=-1).shape

torch.Size([16, 128])

In [117]:
loss = kl.mean()
loss

tensor(0.0004, grad_fn=<MeanBackward0>)

#### KL Div Masked

In [118]:
kl_elem = F.kl_div(p_teacher, p_student, reduction="none")
kl_elem.shape

torch.Size([16, 128, 35])

In [119]:
kl_token = kl_elem.sum(dim=-1)
# dim = -1 > the summation working on the last dimension (B,L,C) > sum for each class
kl_token.shape

torch.Size([16, 128])

In [124]:
mask = batch["attention_mask"]
mask = mask.bool()
mask.float().shape
mask

tensor([[ True,  True,  True,  ..., False, False, False],
        [ True,  True,  True,  ..., False, False, False],
        [ True,  True,  True,  ..., False, False, False],
        ...,
        [ True,  True,  True,  ..., False, False, False],
        [ True,  True,  True,  ..., False, False, False],
        [ True,  True,  True,  ..., False, False, False]])

In [121]:
valid_sum = mask.float().sum()
valid_sum

tensor(92.)

In [202]:
if valid_sum == 0:
    print(torch.tensor(0.0, device=s_result["logits"].device))
kl_sum = (kl_token * mask.float()).sum()
print((kl_sum/valid_sum)*(T*T))

tensor(0.1099, grad_fn=<MulBackward0>)


### Loss Function

In [ ]:
import torch.nn.functional as F

In [ ]:
for T in [0.5, 1, 2, 4, 8]:
    softmax_res = F.softmax(logits/T, dim=-1)
    print(f"With T={T}:\n" + str(softmax_res[:1, :1, :10]))

With T=0.5:
tensor([[[0.0314, 0.0862, 0.0725, 0.0089, 0.0369, 0.0183, 0.0583, 0.0331,
          0.0164, 0.0687]]], grad_fn=<SliceBackward0>)
With T=1:
tensor([[[0.0317, 0.0525, 0.0482, 0.0169, 0.0344, 0.0242, 0.0432, 0.0325,
          0.0229, 0.0469]]], grad_fn=<SliceBackward0>)
With T=2:
tensor([[[0.0305, 0.0393, 0.0376, 0.0223, 0.0318, 0.0267, 0.0356, 0.0309,
          0.0259, 0.0371]]], grad_fn=<SliceBackward0>)
With T=4:
tensor([[[0.0296, 0.0336, 0.0329, 0.0253, 0.0303, 0.0277, 0.0320, 0.0298,
          0.0273, 0.0327]]], grad_fn=<SliceBackward0>)
With T=8:
tensor([[[0.0291, 0.0310, 0.0307, 0.0269, 0.0294, 0.0282, 0.0303, 0.0292,
          0.0280, 0.0306]]], grad_fn=<SliceBackward0>)


## Trainer

## CRF Trial

In [ ]:
import torch
from torchcrf import CRF

In [ ]:
num_tags = 5
model = CRF(num_tags)

In [ ]:
seq_length = 3
batch_size = 2
emissions = torch.randn(seq_length, batch_size, num_tags)
print(emissions.shape)
print(emissions)

torch.Size([3, 2, 5])
tensor([[[-0.9194, -0.4299, -2.3956,  0.7575,  0.5029],
         [ 0.3142, -0.8432, -0.7544, -0.6260, -0.8528]],

        [[-1.1581, -0.1062, -0.3376,  0.0401, -0.3961],
         [ 1.1090, -1.3114, -0.1248, -0.4729,  0.4600]],

        [[-0.5804,  0.7643,  0.8325, -0.6142, -1.6916],
         [-0.8408, -0.5836,  0.6385, -1.1154,  1.0496]]])


In [ ]:
tags = torch.tensor([
    [0, 1], [2, 4], [3, 1]], dtype=torch.long
    )

In [ ]:
model(emissions, tags)

tensor(-12.1175, grad_fn=<SumBackward0>)